version: '3.4'

services:
    main-api:
        build: .
        environment:
            DB_CONNECTION_STRING: "Server=db-server;Database=WorkoutPlannerDB;User=sa;Password=Pa55w0rd2019"
        restart: always
        ports:
            - "7000:80"
        depends_on: 
            - db-server
    db-server:
        image: microsoft/mssql-server-linux:2017-latest
        container_name: db-server
        environment: 
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=Pa55w0rd2019
        ports:
            - "9433:1433"